  export const courses = [
	'Computer Science Engineering',
	'Electrical Engineering',
	'Mechanical Engineering',
	'Civil Engineering',
	'Electronics and Communication Engineering',
	'Chemical Engineering',
	'Aerospace Engineering',
	'Information Technology',
	'Biotechnology',
	'Environmental Engineering',
	'Structural Engineering',
	'Software Engineering',
	'Data Science & Engineering',
	'Embedded Systems',
	'Power Systems',
	'VLSI Design',
	'Thermal Engineering',
	'Artificial Intelligence',
	'Cybersecurity',
	'Robotics',
	'Marketing Management',
	'Finance Management',
	'Human Resource Management',
	'International Business',
	'Operations Management',
	'Entrepreneurship',
	'Retail Management',
	'Hospitality Management',
	'Finance',
	'Marketing',
	'Business Analytics',
	'Healthcare Management',
	'Supply Chain Management',
	'Computer Science',
	'Physics',
	'Chemistry',
	'Mathematics',
	'Biology',
	'Environmental Science',
	'Agricultural Science',
	'Nursing',
	'Biochemistry',
	'Zoology',
	'Software Engineering',
	'Web Development',
	'Cloud Computing',
	'Data Structures and Algorithms',
	'Object-Oriented Programming',
	'Mobile App Development',
	'Data Science',
	'Cybersecurity',
	'Business Intelligence',
	'Political Science',
	'History',
	'Psychology',
	'Economics',
	'Philosophy',
	'Geography',
	'Journalism and Mass Communication',
	'Fine Arts',
	'Public Administration',
	'Education',
	'Diploma in Civil Engineering',
	'Diploma in Mechanical Engineering',
	'Diploma in Electrical Engineering',
	'Diploma in Computer Science',
	'Diploma in Fashion Designing',
	'Diploma in Graphic Designing',
	'Diploma in Hotel Management',
	'Diploma in Business Management',
	'Diploma in Nursing',
	'Diploma in Electrical Technician',
  ];